name: Deploy Terraform AWS Infrastructure

on:
    push:
        branches:
            - main
            - staging
        paths:
            - 'terraform/**'
    pull_request:
        branches:
            - main
            - staging
        paths:
            - 'terraform/**'

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
    REGION: us-east-1
    EKS_CLUSTER_NAME: gitops-cluster



jobs:
    terraform:
        name: Apply Terraform AWS Infrastructure
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init 

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1 # Specify your desired AWS region

            - name: Initialize Terraform
              run: terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}"

            - name: Terraform Format check
              run: terraform fmt -check

            - name: Validate Terraform
              run: terraform validate

            - name: Plan Terraform
              id: plan
              run: terraform plan

            - name: Terraform Plan Status
              if: steps.plan.outcome == 'failure'
              run: |
                echo "Terraform plan failed. Please check the logs for details." 
                exit 1